apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: envworld
  name: envworld
spec:
  containers:
  - env:
    # name of ENV ARG
    - name: TEST_ENV
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: TEST_ENV
    command:
      - /bin/sh
      - -c
      - echo 'start sleep';
        echo 'ENV VALUE:' $TEST_ENV;
        sleep 30;
        echo 'end sleep'
    image: busybox
    name: sleep
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
