apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secretworld
  name: secretworld
spec:
  containers:
  - env:
    # name of ENV ARG
    - name: TEST_ENV
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: TEST_ENV
    command:
      - /bin/sh
      - -c
      - echo 'start sleep';
        cat /my-secret/SECRET/SECRET_KEY1 | xargs -I $ echo 'SECRET KEY1:'$;
        cat /my-secret/SECRET/SECRET_KEY2 | xargs -I $ echo 'SECRET KEY2:'$;
        sleep 30;
        echo 'end sleep'
    image: busybox
    name: sleep
    ports:
      - containerPort: 8080
    resources: {}
    volumeMounts:
    # select volume name
    # mount path in container
    - name: my-secret-volume
      mountPath: /my-secret/SECRET
      readOnly: true
  # define volume
  volumes:
    - name: my-secret-volume
      secret:
        secretName: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
