apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc
spec:
  storageClassName: manual
  # need to match definition of persistant volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
