apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container
  name: multi-container
spec:
  containers:
  # after 30sec, sleep contaier stop and restart
  - command:
    - /bin/sh
    - -c
    - echo 'start sleep';
      sleep 30;
      echo 'end sleep';
    image: busybox
    name: sleep
    ports:
    - containerPort: 80
    resources: {}
  - image: gcr.io/google-samples/hello-app:1.0
    name: helloworld
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
