apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloworld
  name: helloworld
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: helloworld
    ports:
    - containerPort: 8081
    resources: {}
  - image: gcr.io/google-samples/hello-app:2.0
    name: helloworld-v2
    ports:
    - containerPort: 8082
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
